server:
  port: 8002
spring:
  application:
    name: cloud-order-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: order-feign8002
    prefer-ip-address: true

##设置feign客户端超时时间(OpenFeign默认支持ribbon)
#ribbon:
#  #指的是建立连接所用的时间，适用于网络状况正常的情况下, 两端连接所用的时间
#  ReadTimeout: 5000
#  #指的是建立连接后从服务器读取到可用资源所用的时间
#  ConnectTimeout: 5000
#上面的形式已经禁用，新版本的需采用下面的配置设置feignclient的连接和超时时间

#feign:
#  client:
#    config:
#      default:
#        connect-timeout: 5000
#        read-timeout: 5000
feign:
  client:
    config:
#      注意键必须为defalut，值为FeignClientConfiguration对象
      default:
        read-timeout: 5000
        connect-timeout: 5000
logging:
  level:
    com.athome.Service.PaymentFeignService: debug     # feign日志以什么级别监控那个接口


