server:
  port: 8002
spring:
  application:
    name: cloud-consumer-feign-hystrix-order
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版
  instance:
    instance-id: Order-Hystrix8002
    prefer-ip-address: true
feign:
  client:
    config:
      #注意键必须为defalut，值为FeignClientConfiguration对象
      default:
        read-timeout: 5000
        connect-timeout: 5000
  hystrix:
    enabled: true
