server:
  port: 3344

spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      #config服务端配置
      server:
        git:
          uri: https://github.com/135246-ai/springcloud-config.git  #GitHub上面的git仓库名字
          search-paths:
            - springcloud-config  #搜索目录
      label: master    #读取分支
      #启动成功后访问的路径 http://ip:3344/{label}/{application}-{profile}.yml 能访问的配置文件 就表示成功了
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    prefer-ip-address: true
    instance-id: config-server3344