server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      enabled: true
      routes:
        - id: payment_routh  #路由的id，没有固定规则，但要求唯一
          uri: lb://cloud-payment-service  #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/selectById/**  #断言  路径相匹配的进行断言
        - id: payment_routh1  #路由的id，没有固定规则，但要求唯一
          uri: lb://cloud-payment-service  #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/test  #断言  路径相匹配的进行断言
        - id: payment_routh2
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/selectById/**
      discovery:
        locator:
          enabled: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:   #服务提供者provider注册进eureka服务列表内
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    prefer-ip-address: true
    instance-id: cloud-gateway-service9527
