server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com #eureka服务端的实例名称
  client:
    register-with-eureka: false  #不向注册中心注册自己
    fetch-registry: false   #表明自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    #设置与eureka server交互的地址查询服务和注册服务都需要这个地址
    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka/
      defaultZone: http://eureka7002.com:7002/eureka/  #集群相互守望
  server:
    enable-self-preservation: false #关闭自我保护机制，保证不可用服务及时剔除
    eviction-interval-timer-in-ms: 2000  #没过多久进行一次服务剔除（默认60s）